//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroCulture
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingId { get; set; }
        public int CabinId { get; set; }
        public int GuestId { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public int Nights { get; set; }
        public int Adults { get; set; }
        public int Children { get; set; }
        public decimal TotalPrice { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Notes { get; set; }
    
        public virtual Cabins Cabins { get; set; }
        public virtual Users Users { get; set; }
        public virtual Guests Guests { get; set; }
    }
}
