//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroCulture
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabinsStatistics
    {
        public int CabinId { get; set; }
        public string Name { get; set; }
        public int Capacity { get; set; }
        public decimal PricePerNight { get; set; }
        public bool IsAvailable { get; set; }
        public string Amenities { get; set; }
        public Nullable<int> TotalBookings { get; set; }
        public Nullable<int> ActiveBookings { get; set; }
        public Nullable<int> CompletedBookings { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
        public Nullable<int> TotalNightsBooked { get; set; }
    }
}
