//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroCulture
{
    using System;
    using System.Collections.Generic;

    public partial class CabinsWithAmenities
    {
        public int CabinId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int MaxGuests { get; set; }
        public decimal PricePerNight { get; set; }
        public string ImageUrl { get; set; }
        public bool IsActive { get; set; }
        public string Amenities { get; set; }
    }
}
