//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroCulture
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabinAmenities
    {
        public int CabinId { get; set; }
        public int AmenityId { get; set; }
    
        public virtual Amenities Amenities { get; set; }
        public virtual Amenities Amenities1 { get; set; }
        public virtual Cabins Cabins { get; set; }
        public virtual Cabins Cabins1 { get; set; }
    }
}
