//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroCulture
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgroCultureEntities : DbContext
    {
        public AgroCultureEntities()
            : base("name=AgroCultureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amenities> Amenities { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<Cabins> Cabins { get; set; }
        public virtual DbSet<Guests> Guests { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<BookingsDetails> BookingsDetails { get; set; }
        public virtual DbSet<CabinsStatistics> CabinsStatistics { get; set; }
        public virtual DbSet<CabinsWithAmenities> CabinsWithAmenities { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
