//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroCulture
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingsDetails
    {
        public int BookingId { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public int Nights { get; set; }
        public decimal TotalPrice { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CabinId { get; set; }
        public string CabinName { get; set; }
        public decimal PricePerNight { get; set; }
        public int Capacity { get; set; }
        public int GuestId { get; set; }
        public string GuestName { get; set; }
        public string GuestPhone { get; set; }
        public string GuestEmail { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public string CreatedByName { get; set; }
    }
}
